# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RasterTool
                                 A QGIS plugin
 Extract Pixel value from raster files and analyse
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-13
        copyright            : (C) 2019 by NITK
        email                : aishwaryahegde29@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RasterTool class from file RasterTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RasterTool import RasterTool
    return RasterTool(iface)
